### ISSUE TITLE
Tabbing through numbers in Checklist

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-sbg#10]
When entering a number in a checklist, the previous numbers disappear. This only occurs when you use the keypad to type the number, not when you select the item from the dropdown menu. 

![screen shot 2016-01-11 at 2 45 28 pm](https://cloud.githubusercontent.com/assets/5123794/12244509/0d1a0dd2-b872-11e5-89ab-643d06622ebf.png)

![screen shot 2016-01-11 at 2 45 41 pm](https://cloud.githubusercontent.com/assets/5123794/12244510/0e39e41c-b872-11e5-92f5-f27116a5353c.png)

**Comment by BillClinton** [comment]
This should be resolved with the following commit: d0223aa6dee62393316fe075284e0f20d1aa497a

**Comment by BillClinton** [comment]
reassigned for testing/verification

**Comment by ckunkel** [comment]
@themightychris Ready for deployment during the next release (searching and emailing).
