### ISSUE TITLE
"My classes only" button

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-sbg#9]
When selecting the My Classes Only button, the list does not filter correctly. Instead of limiting it to just the courses the teacher is enrolled in as a teacher, the entire list disappears. No errors result in the console. 

![screen shot 2016-01-11 at 2 40 22 pm](https://cloud.githubusercontent.com/assets/5123794/12244346/446f1184-b871-11e5-8b4c-edde87836b8a.png)

**Comment by BillClinton** [comment]
This is corrected by the following two commits:
slate-sbg: 3abf5825f38342d5de238407e3684c014a9e855e
slate: https://github.com/SlateFoundation/slate/commit/a7b3b5096fd4ad1c94c671ec0530374680be6518
